segec_gr55:
  sociedad_co: IDI
  ejercicio: 2026
  periodo_de: 2
  periodo_fins: 2
  grupo_clases_costo: co-6

export:
  filename_prefix: "SEGEC_GR55"
  format: "csv-LEAN-STANDARD"   # csv-LEAN-STANDARD | xlsx-LEAN-STANDARD | 8-TT-STANDARD
  destination: "L"               # L = Local
  directory: "C:\\sap_automate\\exports"
